new references to `development` branch

diff --git a/bin/validate_push b/bin/validate_push
--- a/bin/validate_push
+++ b/bin/validate_push
@@ -7,6 +7,12 @@ branch="$(git rev-parse --abbrev-ref HEAD)"
 if [ "$branch" = "master" ]; then
   echo "You can't push directly to master branch"
   exit 1
+elif [ "$branch" = "main" ]; then
+  echo "You can't push directly to main branch"
+  exit 1
+elif [ "$branch" = "development" ]; then
+  echo "You can't push directly to development branch"
+  exit 1
 elif [ "$branch" = "develop" ]; then
   echo "You can't push directly to develop branch"
   exit 1
