chore(ci): disable frontend items

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -91,25 +91,25 @@ jobs:
             bundle install
             # pnpm install
 
-      - run:
-          name: Download cc-test-reporter
-          command: |
-            mkdir -p ~/tmp
-            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ~/tmp/cc-test-reporter
-            chmod +x ~/tmp/cc-test-reporter
+      # - run:
+      #     name: Download cc-test-reporter
+      #     command: |
+      #       mkdir -p ~/tmp
+      #       curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ~/tmp/cc-test-reporter
+      #       chmod +x ~/tmp/cc-test-reporter
 
       # Swagger verification
-      - run:
-          name: Verify swagger API specification
-          command: |
-            bundle exec rake swagger:build
-            if [[ `git status swagger/swagger.json --porcelain` ]]
-            then
-              echo "ERROR: The swagger.json file is not in sync with the yaml specification. Run 'rake swagger:build' and commit 'swagger/swagger.json'."
-              exit 1
-            fi
-            curl -L https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.3.0/openapi-generator-cli-6.3.0.jar > ~/tmp/openapi-generator-cli-6.3.0.jar
-            java -jar ~/tmp/openapi-generator-cli-6.3.0.jar validate -i swagger/swagger.json
+      # - run:
+      #     name: Verify swagger API specification
+      #     command: |
+      #       bundle exec rake swagger:build
+      #       if [[ `git status swagger/swagger.json --porcelain` ]]
+      #       then
+      #         echo "ERROR: The swagger.json file is not in sync with the yaml specification. Run 'rake swagger:build' and commit 'swagger/swagger.json'."
+      #         exit 1
+      #       fi
+      #       curl -L https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.3.0/openapi-generator-cli-6.3.0.jar > ~/tmp/openapi-generator-cli-6.3.0.jar
+      #       java -jar ~/tmp/openapi-generator-cli-6.3.0.jar validate -i swagger/swagger.json
 
       # we remove the FRONTED_URL from the .env before running the tests
       - run:
@@ -139,26 +139,26 @@ jobs:
           command: bundle exec bundle audit update && bundle exec bundle audit check -v
 
       # Rubocop linting
-      - run:
-          name: Rubocop
-          command: bundle exec rubocop
+      # - run:
+      #     name: Rubocop
+      #     command: bundle exec rubocop
 
-      # ESLint linting
-      - run:
-          name: eslint
-          command: pnpm run eslint
+      # # ESLint linting
+      # - run:
+      #     name: eslint
+      #     command: pnpm run eslint
 
-      - run:
-          name: Run frontend tests
-          command: |
-            mkdir -p ~/build/coverage/frontend
-            ~/tmp/cc-test-reporter before-build
-            pnpm run test:coverage
+      # - run:
+      #     name: Run frontend tests
+      #     command: |
+      #       mkdir -p ~/build/coverage/frontend
+      #       ~/tmp/cc-test-reporter before-build
+      #       pnpm run test:coverage
 
-      - run:
-          name: Code Climate Test Coverage (Frontend)
-          command: |
-            ~/tmp/cc-test-reporter format-coverage -t lcov -o "~/build/coverage/frontend/codeclimate.frontend_$CIRCLE_NODE_INDEX.json"
+      # - run:
+      #     name: Code Climate Test Coverage (Frontend)
+      #     command: |
+      #       ~/tmp/cc-test-reporter format-coverage -t lcov -o "~/build/coverage/frontend/codeclimate.frontend_$CIRCLE_NODE_INDEX.json"
 
       # Run backend tests
       - run:
@@ -175,17 +175,17 @@ jobs:
                               -- ${TESTFILES}
           no_output_timeout: 30m
 
-      - run:
-          name: Code Climate Test Coverage (Backend)
-          command: |
-            ~/tmp/cc-test-reporter format-coverage -t simplecov -o "~/build/coverage/backend/codeclimate.$CIRCLE_NODE_INDEX.json"
+      # - run:
+      #     name: Code Climate Test Coverage (Backend)
+      #     command: |
+      #       ~/tmp/cc-test-reporter format-coverage -t simplecov -o "~/build/coverage/backend/codeclimate.$CIRCLE_NODE_INDEX.json"
 
-      - run:
-          name: List coverage directory contents
-          command: |
-            ls -R ~/build/coverage
+      # - run:
+      #     name: List coverage directory contents
+      #     command: |
+      #       ls -R ~/build/coverage
 
-      - persist_to_workspace:
-          root: ~/build
-          paths:
-            - coverage
+      # - persist_to_workspace:
+      #     root: ~/build
+      #     paths:
+      #       - coverage
